# docker-compose.yml
version: "3"

services:
    client:
        image: node:latest
        working_dir: /app
        volumes:
            - ./:/app
        ports:
            - 8900:8900
        command: sh -c "npm install && npm run serve"